export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    RESET_SELECTED_PRODUCTS: "RESET_SELECTED_PRODUCTS",
    SET_FILTERED_PRODUCTS: "SET_FILTERED_PRODUCTS",
    SET_ADDTOCART_PRODUCTS: "SET_ADDTOCART_PRODUCTS",
}